### ISSUE TITLE
Steam Trading

### ISSUE THREAD

**Issue by mhosseinhz** [winauth/winauth#256] opened 2015-12-05 18:40 UTC
ehem. hi ty for ur nice app but i wana ask can we do trades confirms with this app?  cuz after active Mobile auth ur trade confirms will go to ur mobile and no more emails for it... and if diactive trade confirm then email confirms is more secure so make somthing for it thanx alot :x

sry for my bad English i hope You Know what i mean :\

**Comment by Ulexos** [comment] 2015-12-07 14:47
Having the same problem, WinAuth doesn't send emails anymore when someone offers me a trade (and probably also has steam authentication enabled).

**Comment by winauth** [comment] 2015-12-07 20:43
> WinAuth doesn't send emails anymore when someone offers me a trade

Never did. WinAuth is an authenticator, not a replacement for the Steam mobile app.

However, I'm adding some trade confirmation facilities in the next version, so should be able to view, confirm and reject trades.

**Comment by Ulexos** [comment] 2015-12-08 01:39
>  should be able to view, confirm and reject trades

neat! 👍

**Comment by mhosseinhz** [comment] 2015-12-08 04:43
GL Man I hope u make it faster ^^

our problem in trading will start from 9 dec people who didnt active steam authentication cant trade well they should wait 3 days for every single trade :| Help Us T_T 

Good Luck!

**Comment by winauth** [comment] 2015-12-08 07:02
I'm working on it. Shouldn't take too long, although heads-up, you will need to remove and re-add your authenticator, since we need more data from when it's added in the first place. From my tests, it doesn't seem to reset the 15 day counter as long as you had it on their for that long before.

**Comment by Ulexos** [comment] 2015-12-12 18:58
An update on your prgress regarding this feature would be nice, no need to rush things though

**Comment by winauth** [comment] 2015-12-12 20:24
3.3.7 was just pushed out because of a different issue, including part implementation of Confirmations (not accessible). However, it has the necessary changes to store more of the authenticator information that is required. In order to do trade confirmations, you will need to remove your current authenticator from your account and add a new one with 3.3.7+.

My own experience is that this does not reset the 15-day window, but I haven't tried since the changes on 9th.

I am continuing with the UI for displaying trades and hope to have out in beta in a day or two.

**Comment by winauth** [comment] 2015-12-17 19:26
Confirmations now in 3.4. beta.

https://winauth.com/download/

Please read the description, as it's important to note that if you registered your SteamGuard on an older version on WinAuth, you may need to remove it and add it again.

Be aware this is BETA. Feedback is appreciated. Please use it to test trading confirmation between your own accounts and not with other people, in case of any issues.

**Comment by mhosseinhz** [comment] 2015-12-17 20:07
Wish u the Best! 

Thanx for the time u have spent on this app very usefull

**Comment by lnwc** [comment] 2015-12-18 10:42
The confirmations seem to be working, great job!
One issue I've noticed is that the "remember me" checkbox when you login to the confirmation screen does not seem to work - if I exit WinAuth and launch it again, I have to login again. It's not that big of a problem, but I thought I'd report on it.

**Comment by winauth** [comment] 2015-12-18 17:40
"Remember me" is only intended to be while WinAuth is loaded.

It doesn't store credentials on your machine, so if you close WinAuth your login will be forgotten. But if you minimize or put WinAuth in the system tray, then you can go back into the Confirmations without having to log in again.

**Comment by lnwc** [comment] 2015-12-18 17:52
Oh well, it's a kinda bother since I have multiple accounts and have to restart the computer for one reason or another quite often. Still faster than my previous solution of virtual Android machines so eh, not gonna complain anymore. Thank you for your work:-)

**Comment by winauth** [comment] 2015-12-18 17:54
I'll look at adding a more permanent "remember", but for now that's how it works.

**Comment by Toff-kun** [comment] 2015-12-21 01:57
Would it be possible to create an option to import personal data from SteamDesktopAuthenticator into WinAuth and vice versa? Or is there any way to do that manually? Thanks.

**Comment by Ulexos** [comment] 2015-12-21 02:26
^ Would love to have that option too

**Comment by winauth** [comment] 2015-12-21 02:49
Yes, I was actually working on it. I've coded the importing from Android files (albeit manually) and also adding SteamDesktopAuthenticator. Should be in new beta in next day or so.

**Comment by winauth** [comment] 2015-12-21 06:32
[3.4.2](https://winauth.com/downloads/3.x/WinAuth-3.4.2.zip) is available, which can import from Android files and SteamDesktopAuthenticator. Click Add -> Steam and choose the tab. Let me know if it loads your files.

When viewing confirmations, you choose to to "remember me", which is until WinAuth is closed. Now also "permanently", which will be stored in your config and so work next time.

**Comment by Toff-kun** [comment] 2015-12-21 11:35
Thank you so much, everything worked flawlessly, I was able to import my data from SDA and confirm my trade successfully (which I recently couldn't do with SDA due to some bug).

Is it safe to remember the session permanently? Should there not be any problems if the session is refreshed somehow on Steam's end?

**Comment by RampantZambie** [comment] 2015-12-22 09:35
Is the 3.3.7 version able to confirm trades? And if not will updating reset the 7 day trade cooldown?

**Comment by muckky** [comment] 2015-12-22 20:14
I went back to using 3.4.1 in order to fix my issue but thought I should report the following anyway.

I got the following error when I tried to access trade confirmations(3.4.2):
![error](https://cloud.githubusercontent.com/assets/5849219/11964210/e8a9f3da-a8a0-11e5-84d3-c1e4f1110f76.jpg)

If it helps any, I tried to transfer large amount of items under one trade between two of my accounts. I was successfully able to access the sender confirmation window and accepted the trade but was no longer able to access the confirmation window for both receiver and sender accounts thereafter. However, on my third account with no trades I was able to access the confirmation window. All accounts were using the permanently saved credentials feature.

**Comment by winauth** [comment] 2015-12-22 23:38
@Toff-kun It is safe, in that it is encrypted along with your authenticator. If the session fails to connect (because Steam timed-out or you requested to clear any session) then it will just prompt for the login again. There is an oustanding issue in 3.4.2 where the session does get cleared by Steam and requires a login. So semi-permanent. Trying to fix this.

@muckky Sounds like the session failed an it didn't refresh it as it should. I'll check.

**Comment by winauth** [comment] 2015-12-23 06:34
@muckky this is fixed in 3.4.3. That error was effectively a sessions time-out, which wasn't being handled. It is now and will try and refresh the session or fallback to login form.

**Comment by RampantZambie** [comment] 2015-12-24 08:25
I'm getting an error while clicking confirmations, https://gyazo.com/b8b2b657edb4836804c51bd6bae72c41

What do i do?

**Comment by BakuDM** [comment] 2015-12-25 19:56
I love you!
I was looking for a workaround in the Trade Confirmation and saw this thread.

**Comment by Fl4ilinat0r** [comment] 2015-12-28 22:04
could it be possible to add an auto accept option for the confirmations?
would be useful for people who are running a trade bot.

**Comment by winauth** [comment] 2015-12-28 22:21
Yes, I was working on it for next beta release.

**Comment by Fl4ilinat0r** [comment] 2015-12-28 22:22
awesome!!! 
do you have an ETA ?

**Comment by winauth** [comment] 2015-12-28 22:22
Not really, order of days, not weeks.

**Comment by Fl4ilinat0r** [comment] 2015-12-28 22:23
(again) Awesome !!!

**Comment by RampantZambie** [comment] 2015-12-28 22:56
![b8b2b657edb4836804c51bd6bae72c41](https://cloud.githubusercontent.com/assets/16399209/12026834/049cdb0c-ae0a-11e5-8208-22aac50bfaca.png)

Yo winauth do you know why i'm getting this error?

**Comment by winauth** [comment] 2015-12-28 23:03
@RampantZambie I don't. What did you do? Just showing trades? Can you please [create a new issue](https://github.com/winauth/winauth/issues/new).

**Comment by RampantZambie** [comment] 2015-12-28 23:05
k i've just created one :P

**Comment by BakuDM** [comment] 2016-01-01 00:21
You said to remove the Authenticator if you registered the Steam Guard before 3.3.7, but I can still use the same configurations and still use the same authenticators for my others games? Or do I need to remove the Authenticator for everything that I registered before 3.3.7?

**Comment by BakuDM** [comment] 2016-01-01 01:05
And for me it reseted the 7 days thing, when I tried to trade with a friend, a message saying that I am not using a Mobile Authenticator for 7 days and for this reason they will hold the items for 72 hours.
Well, shit. :C

**Comment by winauth** [comment] 2016-01-01 01:44
@BakuDM It's just the Steam authenticator. We didn't collect all the information needed for trade confirmations, so it is the only way from earlier versions. Everything else works as before. Please make sure you keep backups if you're using the Beta.

Sorry it reset. Does your friend also have an authenticator? They must to avoid the 72 hrs. When I tried it didn't reset, not sure why. There would have been no way around this so would have been done at some point.

**Comment by BakuDM** [comment] 2016-01-01 03:07
Yeah, he has.
But that's fine, at least after the 7 days thing I will be able to trade again.
Thank you for your work. :p

**Comment by Fl4ilinat0r** [comment] 2016-01-04 07:01
any progress on the auto accept confirmations ?

**Comment by anapot1** [comment] 2016-01-13 03:18
![winauth error](https://cloud.githubusercontent.com/assets/16677777/12283859/aee3805c-b9e5-11e5-9b0e-05f91236da3a.png)

additional information. .
- i have already verified the 7 days steam guard authenticator using the version 3.3.7. but since it has no trade confirmation i download the version 3.4.3 and replace the old version. after that the 7 days trade restriction has reset. . but i can sell and trade in steam market/ there is no restriction inside the steam. . except for other website trading like betting site. is it possible that the cause of error is the 7 days trade restriction? . . need and update and clear response about this error.

- confirmation of the create list item, in steam (when you sell items must be clarify).
   because it has to be no restriction since it's already used 7 days authenticator.

- confirmation of steam trade offer and trading to other site, like betting site(dota2lounge, vpgame, dotabestyolo, etc..) must be clarify also since it has 7 days restriction.

---------------thanks and more power------------------------

**Comment by csamartins** [comment] 2016-01-13 03:23
Not wanting to hijack this topic, any idea when the source code with confirmations support is going to be pushed? I wouldn't mind to have a look at that :)

Cheers

**Comment by winauth** [comment] 2016-01-13 05:18
@anapot1 This is resolved in [3.4.8](https://winauth.com/downloads/3.x/WinAuth-3.4.8.zip) if you want to try that. If not, please can you create a new Issue.

**Comment by winauth** [comment] 2016-01-13 05:21
Sorry everyone. Been down with a bug (the human kind). Had a working version of latest veta with notifications for the auto-trade feature, but didn't like how they were looking, so was in middle of re-working it. Will try and get a new version and its source pushed out in next day or two.

**Comment by Toff-kun** [comment] 2016-01-13 05:32
@winauth Decided to try 3.4.8 for testing purposes, and it gives me an error every time I log in to check my confirmations. I always tick 'remember me' but don't tick 'permanently', if that info is of any use to you. Once I click 'Continue' and try to login again it gets me to the confirmations screen successfully. Error report sent.

**Comment by winauth** [comment] 2016-01-13 05:38
@Toff-kun Did it generate a winauth.log file? If so, can you email it. winauth@gmail.com

**Comment by Toff-kun** [comment] 2016-01-13 05:49
@winauth Yes, it did. Email sent.

**Comment by winauth** [comment] 2016-01-20 06:56
Latest beta to try. Please backup your data first.

https://winauth.com/downloads/3.x/WinAuth-3.4.10.zip

This provide notifications for new Steam Confirmations and the ability to auto-confirm them. Go into the Confirmations window, make sure you are "remembered" permanently, you can set up a polling time in minutes and and action (notify or auto-confirm).

The notification will display in the lower right. Clicking it will open your Confirmations page. An auto-confirm also shows a notification.

I'm closing this Issue as hard to keep track of actual related issues. If you have a problem, please create a new issue. Thanks.

**Closed by winauth** 2016-01-20 06:56 UTC

**Comment by winauth** [comment] 2016-01-29 07:19
New version [3.4.13](https://winauth.com/downloads/3.x/WinAuth-3.4.13.zip) that has fixes in remembering Steam login.
