### ISSUE TITLE
Error when opening

### ISSUE THREAD

**Issue by BakuDM** [winauth/winauth#235] opened 2015-10-25 03:40 UTC
For some reason I am getting this error when I try to open WinAuth.

http://i.imgur.com/nlFnqMe.png

I opened it the first time, added a Google Authenticator, a Password and now when I try to open it I get this error, I am already using the latest version (3.3), I have no idea why it isn't working. :C

-Edit

If I click to check Updates:
http://i.imgur.com/rl45m3F.png

I thought the 3.3 version in the Download page was the latest version...

Tried to delete the winauth.xml and try again, still getting the error.

**Comment by idefixx** [comment] 2015-10-25 05:00
Same for me. There is a serious bug in this version. I can only assume its a version mismatch.

As a matter of fact I can start WinAuth, close it without making adding anything and when I reopen the tool it throws that exact error even though the xml version tag seems to be alright.

I tried different backups from different version but unsurprisingly it doesn't work. Setting version to 0.0 does work once makes WinAuth freak and set the value back 3.3 which makes it throw+quit the next time you start it.

This is my current clean config with which WinAuth will not start.

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<WinAuth version="3.3">
  <alwaysontop>false</alwaysontop>
  <usetrayicon>false</usetrayicon>
  <startwithwindows>false</startwithwindows>
  <autosize>true</autosize>
  <left>750</left>
  <top>430</top>
  <width>0</width>
  <height>0</height>
</WinAuth>
```

**Comment by winauth** [comment] 2015-10-25 05:02
I'm looking into it

**Comment by winauth** [comment] 2015-10-25 05:17
I've pulled the version just in case, but when I ran the same on a test machine I didn't get the same errors.

Where do you have the winauth.xml located? Do you keep it in the default place of \Users\<username>\AppData\Roaming\Winauth?

@idefixx Can you please post the actual winauth.xml file that you posted the content of above. I want to check it here, in case it's a file encoding problem.

**Comment by BakuDM** [comment] 2015-10-25 05:18
Oh, sorry, forgot to mention, I am using Windows 10 Pro x64.

Yes, my winauth.xml is in the default place (appdata/roaming/winauth).

**Comment by winauth** [comment] 2015-10-25 05:20
I can confirm that the  version check is still referring to 3.1.8. This would have been updated overnight, but I've stopped it too.

@BakuDM Do you have a winauth.xml file you can post too?

**Comment by BakuDM** [comment] 2015-10-25 05:24
I have, but I have no idea how to post a code here without screwing it up.
And there is no problem posting the xml with my encrypted password?

**Comment by winauth** [comment] 2015-10-25 05:28
Would you be able to email it to me? Even just a file with a dummy authenticator that causes the problem

winauth@gmail.com

**Comment by BakuDM** [comment] 2015-10-25 05:31
I made a random Trion Authenticator just to test, still getting the error and this is the xml.

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<WinAuth version="3.3">
  <alwaysontop>false</alwaysontop>
  <usetrayicon>false</usetrayicon>
  <startwithwindows>false</startwithwindows>
  <autosize>true</autosize>
  <left>473</left>
  <top>274</top>
  <width>0</width>
  <height>0</height>
  <WinAuthAuthenticator id="2c6e65aa-71cf-437e-b01b-ff28713883af" type="WinAuth.TrionAuthenticator">
    <name>Trion</name>
    <created>1445751002914</created>
    <autorefresh>false</autorefresh>
    <allowcopy>false</allowcopy>
    <copyoncode>false</copyoncode>
    <hideserial>false</hideserial>
    <skin></skin>
    <authenticatordata>
      <servertimediff>2035</servertimediff>
      <lastservertime>635813406055754273</lastservertime>
      <secretdata>3645584A444E4A4E4D395958444A32544533474D	8|4C5A50502D454E58572D59465951|363835433637383435443746414636</secretdata>
    </authenticatordata>
  </WinAuthAuthenticator>
</WinAuth>

```

**Comment by idefixx** [comment] 2015-10-25 05:32
Yes default location. This is actually a clean install of Win7 that I did last week. WinAuth never ran on it before a couple today.

https://www.dropbox.com/s/fe1idx1g4k83y9h/winauth.zip?dl=0

(ziped it so db doesn't mess with it... who knows)

**Comment by BakuDM** [comment] 2015-10-25 05:34
Like @idefixx said, even if you don't setup any Authenticator you still get the error.

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<WinAuth version="3.3">
  <alwaysontop>false</alwaysontop>
  <usetrayicon>false</usetrayicon>
  <startwithwindows>false</startwithwindows>
  <autosize>true</autosize>
  <left>473</left>
  <top>274</top>
  <width>0</width>
  <height>0</height>
</WinAuth>
```

**Comment by idefixx** [comment] 2015-10-25 05:45
@winauth Well I upgraded to .NET 4.6, no changes.

Also the program doesn't do a clean shutdown the tray icon isn't cleaned up after that error... just in case it helps.

**Comment by winauth** [comment] 2015-10-25 05:46
@BakuDM I actually get a different error with that Trion authenticator, unrelated to this I think. But that "empty" xml you posted loaded.

What region do you have set in Windows, i.e. in Start->Control Panel->Region?

**Comment by BakuDM** [comment] 2015-10-25 05:47
Home Location: USA

**Comment by winauth** [comment] 2015-10-25 05:49
You use US-English date and number formatting? i.e. 3.3 not 3,3

**Comment by BakuDM** [comment] 2015-10-25 05:50
Maybe is something related to the version, since the "Check for Updates" is showing 3.1.8 as latest.
Yours is showing this too?

**Comment by BakuDM** [comment] 2015-10-25 05:50
No.
Let me change to see if it works.

**Comment by idefixx** [comment] 2015-10-25 05:52
I used German (Germany)... after switching to English (US) its working

**Comment by BakuDM** [comment] 2015-10-25 05:52
Well, changing the format worked.

**Comment by winauth** [comment] 2015-10-25 05:53
There's a mistake in the parsing of the "3.3", which when set to European languages would see it as "3", since it expected "3,3".

**Comment by BakuDM** [comment] 2015-10-25 05:54
So, there is a way to workaround it or do I need to use USA format? D:

**Comment by winauth** [comment] 2015-10-25 05:55
You can use US number formatting as a workaround. I'm going to release 3.3.1 soon.

**Comment by idefixx** [comment] 2015-10-25 05:57
@winauth You are one awesome dev. Thx for the quick response mate!

**Comment by winauth** [comment] 2015-10-25 05:58
@idefixx No problem...although good job I happened to be up still :)

**Comment by idefixx** [comment] 2015-10-25 05:58
@winauth 6:58 am here ;)

**Comment by BakuDM** [comment] 2015-10-25 06:08
Thank you bro, I thought I would get locked out of my Account until tomorrow. haha

**Comment by winauth** [comment] 2015-10-25 06:15
3.3.1 is up. https://winauth.com/downloads/3.x/WinAuth-3.3.1.zip

The version check will still say 3.1.8 for a while. I'll leave that for a day or so,  just to do some more sanity checking, so I don't have thousands of people upgrading with problems!

Thanks to you both for posting the error and helping me find the issue.

**Comment by BakuDM** [comment] 2015-10-25 06:16
To upgrade I just delete the old WinAuth.exe and use this one?

**Comment by winauth** [comment] 2015-10-25 06:21
Yes, just replace the previous 3.3.0 winauth.exe file with this one.

**Closed** 2015-12-01 16:58 UTC
